apiVersion: apps/v1
kind: Deployment
metadata:
  name: polizai-db
  labels:
    app: polizai-db
    version: postgres12.6-alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polizai-db
  template:
    metadata:
      labels:
        app: polizai-db
    spec:
      containers:
      - name: polizai-db
        image: postgres:12.6-alpine
        ports:
        - containerPort: 5432
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 45
          periodSeconds: 20
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: polizai-db-secret
              key: db-name
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: polizai-db-secret
              key: db-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: polizai-db-secret
              key: db-pass
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d
          name: entrypoint-initdb
      volumes:
      - name: entrypoint-initdb
        persistentVolumeClaim:
          claimName: polizai-db-pvc-volume 

