apiVersion: v1
kind: PersistentVolume
metadata:
  name: polizai-db-pv-volume 
  labels:
    app: polizai-db
    type: local
spec:
  storageClassName: manual 
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "$DATAPATH" 
