apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: polizai-db-pvc-volume 
  labels:
    app: polizai-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
