apiVersion: apps/v1
kind: Deployment
metadata:
  name: polizai-be
  labels:
    app: polizai-be
spec:
  replicas: 2
  selector:
    matchLabels:
      app: polizai-be
  template:
    metadata:
      labels:
        app: polizai-be
    spec:
      containers:
      - name: polizai-be
        image: angelalonso/polizai-phrase-backend:v0.1
        ports:
        - containerPort: 8000
        env:
        - name: PHRASES_FILE
          value: "/data/dirtyharry_eastwood.txt"
        volumeMounts:
        - mountPath: /data # Path of the volume in the container
          name: data-volume

      volumes:
      - name: data-volume
        hostPath:
          path: /microk8s/polizai-be-data # Path of the directory on the Host (node). I add a link to the actual data
          type: Directory
