FROM rustlang/rust:nightly as cargo-build 
                                        
RUN apt-get update                      
RUN apt-get install musl-tools -y       
RUN which cargo                         
RUN /usr/local/cargo/bin/cargo install diesel_cli --no-default-features --features postgres
RUN /usr/local/cargo/bin/rustup target add x86_64-unknown-linux-musl                                     
RUN USER=root /root/.cargo/bin/cargo new --bin polizai_back 
                                        
WORKDIR /polizai_back                   
                                        
COPY ./Cargo.toml ./Cargo.toml          
COPY ./Cargo.lock ./Cargo.lock          
                                        
RUN RUSTFLAGS=-Clinker=musl-gcc /root/.cargo/bin/cargo build --release --target=x86_64-unknown-linux-musl 
RUN rm -f target/x86_64-unknown-linux-musl/release/deps/polizai_back* 
RUN rm src/*.rs                         
                                        
COPY ./src ./src                        
                                        
RUN RUSTFLAGS=-Clinker=musl-gcc /root/.cargo/bin/cargo build --release --target=x86_64-unknown-linux-musl
                                        
FROM alpine:latest                      
                                        
COPY --from=cargo-build /polizai_back/target/x86_64-unknown-linux-musl/release/main . 
COPY ./data .                           
                                        
CMD ["./main"]                          
                             
