[package]
name = "data_worker"
version = "0.1.0"
authors = ["Angel Alonso <alonsofonseca.angel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.0.0"
